PetPharm/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('project.urls', namespace='project')),

]

project/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import *
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy


class MyHackedView(auth_views.PasswordResetView):
    success_url = reverse_lazy('project:password_reset_done')


app_name = 'project'

urlpatterns = [
    path('', all_medicines, name='all_medicines'),
    path('<int:y>/<int:m>/<int:d>/<slug:slug>/', detailed_medicine,
         name='detailed_medicine'),
    path('<int:medicine_id>/share/', share_medicine, name='share_medicine'),
    path('create/', create_medicine, name='create_medicine'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('password_reset/', MyHackedView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        success_url=reverse_lazy('project:password_reset_complete'),
    ), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('profile/', profile, name='profile'),
    path('register/', register, name='register'),
    path('edit_profile/', edit_profile, name='edit_profile'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/models.py
from django.db import models
from django.db.models import DecimalField
from django_bookmark_base.models import BookmarkModel
from django.conf import settings
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone


# Create your models here.


class Medicine(models.Model):
    title = models.CharField(max_length=255, verbose_name='Заголовок')
    slug = models.SlugField(max_length=255,
                            unique_for_date='publish')

    SUPPLIED_TYPE = [
        ('Не указано', 'Не указано'),
        ('Таблетки', 'Таблетки'),
        ('Порошок', 'Порошок'),
        ('Капсулы', 'Капсулы'),
        ('Драже', 'Драже'),
        ('Гранулы', 'Гранулы'),
        ('Мазь', 'Мазь'),
        ('Крем', 'Крем'),
        ('Паста', 'Паста'),
        ('Гель', 'Гель'),
        ('Раствор', 'Раствор'),
        ('Суспензия', 'Суспензия'),
        ('Капли', 'Капли'),
        ('Сироп', 'Сироп'),
        ('Аэрозоль', 'Аэрозоль'),
        ('Другое', 'Другое'),
    ]

    SUPPLIED_TYPE = models.CharField(
        verbose_name='Тип',
        max_length=100,
        choices=SUPPLIED_TYPE,
        default='Не указано'
    )
    PHARMACY = [
        ('Нет в наличии', 'Нет в наличии'),
        ('Алибегова ул., д. 13/1', 'Алибегова ул., д. 13/1'),
        ('Воронянского ул., д. 17а', 'Воронянского ул., д. 17а'),
        ('Горецкого ул., д. 2', 'Горецкого ул., д. 2'),
        ('Городецкая ул., д. 30', 'Городецкая ул., д. 30'),
        ('Дзержинского пр-т, д. 119', 'Дзержинского пр-т, д. 119'),
    ]

    PHARMACY = models.CharField(
        verbose_name='Аптека',
        max_length=500,
        choices=PHARMACY,
        default='Нет в наличии'
    )

    body = models.TextField()

    publish = models.DateTimeField(default=timezone.now, verbose_name='Добавлено')

    updated = models.DateTimeField(auto_now=True, verbose_name='Обновлено')

    def get_absolute_url(self):
        return reverse('project:detailed_medicine',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day,
                             self.slug])

    class Meta:
        ordering = ['-updated']


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE)
    birth = models.DateTimeField(blank=True, null=True)
    photo = models.ImageField(blank=True, upload_to="user/%Y/%m/%d")

project/forms.py
from django import forms
from . import models

from django.contrib.auth.models import User


class EmailMedicineForm(forms.Form):
    name = forms.CharField(max_length=255)
    to_email = forms.EmailField()
    comment = forms.CharField(required=False,
                              widget=forms.Textarea)


class MedicineForm(forms.ModelForm):
    class Meta:
        model = models.Medicine
        fields = ('title', 'body')


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Повторите пароль', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('bad password')
        return cd['password']


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'email')


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = models.Profile
        fields = ('birth', 'photo')


class MedicineForm(forms.ModelForm):
    class Meta:
        model = models.Medicine
        fields = ('title', 'body', 'SUPPLIED_TYPE', 'PHARMACY')

project/views.py
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from django.core.paginator import Paginator
from django.contrib.auth.models import User
from . import models
from . import forms
from django.db.models import Q
from django.contrib.auth.decorators import login_required


# Create your views here.

SUBJECT = '{name} Wants to share material "{title}" with you.'

BODY = ("{title} at {uri}. {name} shared material with you. "
        "Please take"  "a look at it. {name} has provided "
        "next comment: {comment} ")


def all_medicines(request):
    search_query = request.GET.get('search', '')

    if search_query:
        medicines = models.Medicine.objects.filter(Q(title__icontains=search_query) | Q(body__icontains=search_query))
    else:
        medicines = models.Medicine.objects.all()
    paginator = Paginator(medicines, 5)
    page_number = request.GET.get('page', 1)
    page = paginator.get_page(page_number)

    is_paginated = page.has_other_pages()

    if page.has_previous():
        prev_url = '?page={}'.format(page.previous_page_number())
    else:
        prev_url = ''

    if page.has_next():
        next_url = '?page={}'.format(page.next_page_number())
    else:
        next_url = ''

    context = {
        'page_object': page,
        'is_paginated': is_paginated,
        'next_url': next_url,
        'prev_url': prev_url,
    }

    return render(request, "medicines/all_medicines.html",
                  context=context)


@login_required
def detailed_medicine(request, y, m, d, slug):
    medicine = get_object_or_404(models.Medicine,
                                 publish__year=y,
                                 publish__month=m,
                                 publish__day=d,
                                 slug=slug)
    return render(request, "medicines/detailed_medicine.html",
                  {"medicine": medicine})


def share_medicine(request, medicine_id):
    medicine = get_object_or_404(models.Medicine, id=medicine_id)

    sent = False

    if request.method == "POST":
        form = forms.EmailMedicineForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            uri = request.build_absolute_uri(
                medicine.get_absolute_url(),
            )

            subject = SUBJECT.format(name=cd['name'],
                                     title=medicine.title)
            body = BODY.format(title=medicine.title,
                               uri=uri,
                               name=cd['name'],
                               comment=cd['comment'],
                               )
            send_mail(subject, body, 'admin@my.com', [cd['to_email'], ])
            sent = True
    else:
        form = forms.EmailMedicineForm()

    return render(request,
                  'medicines/share.html',
                  {'medicine': medicine, 'form': form, 'sent': sent})


def profile(request):
    return render(request, "profile.html", {'user': request.user})


def register(request):
    if request.method == "POST":
        form = forms.UserRegistrationForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            new_user = form.save(commit=False)
            new_user.set_password(cd['password'])
            new_user.save()
            models.Profile.objects.create(user=new_user)

            return render(request, "registration_complete.html",
                          {"user": new_user})

    else:
        form = forms.UserRegistrationForm()
    return render(request, "register.html", {'form': form})


def edit_profile(request):
    if request.method == "POST":
        user_form = forms.UserEditForm(request.POST, instance=request.user)
        profile_form = forms.ProfileEditForm(request.POST,
                                             instance=request.user.profile,
                                             files=request.FILES)
        if all((user_form.is_valid(), profile_form.is_valid())):
            user_form.save()
            if not profile_form.cleaned_data['photo']:
                profile_form.cleaned_data['photo'] = request.user.profile.photo
            profile_form.save()
            return render(request, "profile.html", {'user': request.user})

    else:
        user_form = forms.UserEditForm(instance=request.user)
        profile_form = forms.ProfileEditForm(request.POST, instance=request.user.profile)

    return render(request, "edit_profile.html", {'user_form': user_form,
                                                 'profile_form': profile_form})


def create_medicine(request):
    if request.method == "POST":
        medicine_form = forms.MedicineForm(request.POST)
        if medicine_form.is_valid():
            new_medicine = medicine_form.save(commit=False)
            new_medicine.author = User.objects.first()
            new_medicine.slug = new_medicine.title.replace(" ", "-")
            new_medicine.save()

            return render(request, "medicines/detailed_medicine.html",
                          {"medicine": new_medicine})

    else:
        medicine_form = forms.MedicineForm()

    return render(request,
                  'medicines/create.html',
                  {'form': medicine_form})

project/templates/base.html
{% load bootstrap4 %}
{% load static %}
{% bootstrap_css %}
{% bootstrap_javascript %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
<link rel="stylesheet" href="{% static 'style.css' %}" >

<header>
    <nav class="navbar navbar-light" style="background-color: #b08fb0;">
        <a class="navbar-brand" href="{% url 'project:all_medicines' %}" style="color: #7c327c">
            <h1> PetPharm </h1> </a>
        <form class="form-inline my-2 my-lg-0" action="{% url 'project:all_medicines' %}">
            <input class="form-control mr-sm-2" type="Поиск лекарства" placeholder="Поиск лекарства" aria-label="Поиск лекарства" name="search">
            <button class="btn btn-light" type="submit">Поиск</button>
        </form>
        {% if request.user.is_authenticated %}




            <div class="profile-image">
            {% if profile.image %}
                <p><img src="{{profile.image.url}}"></p>
            {% else %}
                <p></p>
            {% endif %}




                <a href="{% url "project:profile" %}" class="btn btn-light">Мой профиль</a>
                <a href="{% url "project:logout" %}" class="btn btn-light">Выйти </a>
            </div>

            {% else %}
            <div>
                <a href="{% url "project:login" %}" class="btn btn-light">Войти </a>
                <a href="{% url "project:register" %}" class="btn btn-light">Зарегистрироваться </a>
            </div>
        {% endif %} </nav>
    </nav>
</header>
</head>
<body>


<div class="container-flex mt-5" >
    <div class="row" >

        <div class="col-6 offset-md-2" >

        {% block body %}
            Content
        {% endblock %}

    </div>
    <div class="col-sm-10">

    </div>
</div>

</div>

{% if request.user.is_authenticated and request.user.is_staff %}
    <div class="admin-panel">
    <a href="/admin" class="btn btn-danger"> Admin</a>
    {% block admin-panel %} {% endblock %}
{% endif %}
</div>
</body>
</html>

project/templates/edit_profile.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% load crispy_forms_tags %}


{% block title %}
    Edit profile
{% endblock %}

{% block body %}
    <div class="container rounded bg-white mt-5 mb-5">
        <div class="row">
            <div class="col-md-3 right">
                <div class="d-flex flex-column align-items-center text-center p-3 py-5">
                    {% if user.profile.photo %}
                        <img src="{{ user.profile.photo.url }}" alt="Нет фото" class="rounded float-left d-block">
                    {% else %}
                        <p> </p>
                    {% endif %}
                    <p><img src="{{post.image.url}}"></p>
                    <span class="font-weight-bold">
                        {{ user.first_name }}
                    </span>
                    <span class="text-black-50">
                        {{ user.email}}
                    </span>
                    <span> </span>
                </div>
            </div>
             <div class="col-md-9">
                 <div class="p-3 py-5">
                     <div class="d-flex align-items-right mb-3">
                         <h4 class="text-right">Редактирование профиля</h4>
                     </div>
                     <div class="row mt-2">
                         <form action="." method="post" enctype="multipart/form-data">
                             {{ user_form | crispy }}
                             {{ profile_form | crispy }}
                             {% csrf_token %}
                             <input type="submit" value="Изменить" class="btn btn-light">
                         </form>
                     </div>
                </div>
             </div>
        </div>
{% endblock %}

project/templates/profile.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
    Profile
{% endblock %}

{% block body %}
     <div class="container rounded bg-white mt-5 mb-5">
        <div class="row">
            <div class="col-md-3 right">
                <div class="d-flex flex-column align-items-center text-center p-3 py-5">
                   {% if user.profile.photo %}
                       <img src="{{ user.profile.photo.url }}" alt="Нет фото" class="rounded float-left d-block">

                    {% else %}
                       <p> </p>
                    {% endif %}
                    <span class="font-weight-bold">
                        {{ user.first_name }}
                    </span>
                    <span class="text-black-50">
                        {{ user.email}}
                    </span>
                    <span> </span>
                </div>
            </div>
             <div class="col-md-9">
                 <div class="p-3 py-5">
                     <div class="d-flex align-items-right mb-3">
                         <h4 class="text-right">Мой профиль</h4> <br>
                     </div>
                     <div class="information">
                         <p> Имя: {{ user.first_name }} </p>
                         <p> Адрес электронной почты: {{ user.email }}</p>
                         <p> Дата рождения: {{ user.profile.birth }}</p>
                     </div>

                     <div class="row mt-2">
                         <form action="." method="post" enctype="multipart/form-data">
                             {% csrf_token %}
                         </form>
                     </div>
                     <div class="edit-button">
                         <a href="{% url "project:edit_profile" %}" class="btn btn-light"> Изменить информацию о себе </a>
                     </div>

                </div>
             </div>
        </div>
{% endblock %}

project/templates/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
Зарегистрироваться
{% endblock %}

{% block body %}
        <h1>Зарегистрироваться</h1>
        <form action="." method="post">
            {{ form|crispy }}
            {% csrf_token %}
            <input type="submit" value="Зарегистрироваться!" class="btn btn-light">
        </form>
{% endblock %}

project/templates/registration_complete.html
{% extends 'base.html' %}

{% block title %}
    Registration complete
{% endblock %}

{% block body %}
    <div class="alert alert-success" role="alert">
        <h1>Добро пожаловать {{ user.first_name }}</h1>
        Вы были успешно зарегистрированы. Теперь вы можете
        <a href="{% url "project:login" %}">войти в профиль </a><br>
    </div>

<a href="{% url "project:all_medicines" %}" class="btn btn-light"> Все препараты </a>
{% endblock %}