PetPharm/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('project.urls', namespace='project')),

]

project/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import *
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy


class MyHackedView(auth_views.PasswordResetView):
    success_url = reverse_lazy('project:password_reset_done')


app_name = 'project'

urlpatterns = [
    path('', all_medicines, name='all_medicines'),
    path('<int:y>/<int:m>/<int:d>/<slug:slug>/', detailed_medicine,
         name='detailed_medicine'),
    path('<int:medicine_id>/share/', share_medicine, name='share_medicine'),
    path('create/', create_medicine, name='create_medicine'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('password_reset/', MyHackedView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        success_url=reverse_lazy('project:password_reset_complete'),
    ), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('profile/', profile, name='profile'),
    path('register/', register, name='register'),
    path('edit_profile/', edit_profile, name='edit_profile'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/models.py
from django.db import models
from django.db.models import DecimalField
from django_bookmark_base.models import BookmarkModel
from django.conf import settings
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone


# Create your models here.


class Medicine(models.Model):
    title = models.CharField(max_length=255, verbose_name='Заголовок')
    slug = models.SlugField(max_length=255,
                            unique_for_date='publish')

    SUPPLIED_TYPE = [
        ('Не указано', 'Не указано'),
        ('Таблетки', 'Таблетки'),
        ('Порошок', 'Порошок'),
        ('Капсулы', 'Капсулы'),
        ('Драже', 'Драже'),
        ('Гранулы', 'Гранулы'),
        ('Мазь', 'Мазь'),
        ('Крем', 'Крем'),
        ('Паста', 'Паста'),
        ('Гель', 'Гель'),
        ('Раствор', 'Раствор'),
        ('Суспензия', 'Суспензия'),
        ('Капли', 'Капли'),
        ('Сироп', 'Сироп'),
        ('Аэрозоль', 'Аэрозоль'),
        ('Другое', 'Другое'),
    ]

    SUPPLIED_TYPE = models.CharField(
        verbose_name='Тип',
        max_length=100,
        choices=SUPPLIED_TYPE,
        default='Не указано'
    )
    PHARMACY = [
        ('Нет в наличии', 'Нет в наличии'),
        ('Алибегова ул., д. 13/1', 'Алибегова ул., д. 13/1'),
        ('Воронянского ул., д. 17а', 'Воронянского ул., д. 17а'),
        ('Горецкого ул., д. 2', 'Горецкого ул., д. 2'),
        ('Городецкая ул., д. 30', 'Городецкая ул., д. 30'),
        ('Дзержинского пр-т, д. 119', 'Дзержинского пр-т, д. 119'),
    ]

    PHARMACY = models.CharField(
        verbose_name='Аптека',
        max_length=500,
        choices=PHARMACY,
        default='Нет в наличии'
    )

    body = models.TextField()

    publish = models.DateTimeField(default=timezone.now, verbose_name='Добавлено')

    updated = models.DateTimeField(auto_now=True, verbose_name='Обновлено')

    def get_absolute_url(self):
        return reverse('project:detailed_medicine',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day,
                             self.slug])

    class Meta:
        ordering = ['-updated']


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE)
    birth = models.DateTimeField(blank=True, null=True)
    photo = models.ImageField(blank=True, upload_to="user/%Y/%m/%d")

project/forms.py
from django import forms
from . import models

from django.contrib.auth.models import User


class EmailMedicineForm(forms.Form):
    name = forms.CharField(max_length=255)
    to_email = forms.EmailField()
    comment = forms.CharField(required=False,
                              widget=forms.Textarea)


class MedicineForm(forms.ModelForm):
    class Meta:
        model = models.Medicine
        fields = ('title', 'body')


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Повторите пароль', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('bad password')
        return cd['password']


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'email')


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = models.Profile
        fields = ('birth', 'photo')


class MedicineForm(forms.ModelForm):
    class Meta:
        model = models.Medicine
        fields = ('title', 'body', 'SUPPLIED_TYPE', 'PHARMACY')

project/views.py
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from django.core.paginator import Paginator
from django.contrib.auth.models import User
from . import models
from . import forms
from django.db.models import Q
from django.contrib.auth.decorators import login_required


# Create your views here.

SUBJECT = '{name} Wants to share material "{title}" with you.'

BODY = ("{title} at {uri}. {name} shared material with you. "
        "Please take"  "a look at it. {name} has provided "
        "next comment: {comment} ")


def all_medicines(request):
    search_query = request.GET.get('search', '')

    if search_query:
        medicines = models.Medicine.objects.filter(Q(title__icontains=search_query) | Q(body__icontains=search_query))
    else:
        medicines = models.Medicine.objects.all()
    paginator = Paginator(medicines, 5)
    page_number = request.GET.get('page', 1)
    page = paginator.get_page(page_number)

    is_paginated = page.has_other_pages()

    if page.has_previous():
        prev_url = '?page={}'.format(page.previous_page_number())
    else:
        prev_url = ''

    if page.has_next():
        next_url = '?page={}'.format(page.next_page_number())
    else:
        next_url = ''

    context = {
        'page_object': page,
        'is_paginated': is_paginated,
        'next_url': next_url,
        'prev_url': prev_url,
    }

    return render(request, "medicines/all_medicines.html",
                  context=context)


@login_required
def detailed_medicine(request, y, m, d, slug):
    medicine = get_object_or_404(models.Medicine,
                                 publish__year=y,
                                 publish__month=m,
                                 publish__day=d,
                                 slug=slug)
    return render(request, "medicines/detailed_medicine.html",
                  {"medicine": medicine})


def share_medicine(request, medicine_id):
    medicine = get_object_or_404(models.Medicine, id=medicine_id)

    sent = False

    if request.method == "POST":
        form = forms.EmailMedicineForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            uri = request.build_absolute_uri(
                medicine.get_absolute_url(),
            )

            subject = SUBJECT.format(name=cd['name'],
                                     title=medicine.title)
            body = BODY.format(title=medicine.title,
                               uri=uri,
                               name=cd['name'],
                               comment=cd['comment'],
                               )
            send_mail(subject, body, 'admin@my.com', [cd['to_email'], ])
            sent = True
    else:
        form = forms.EmailMedicineForm()

    return render(request,
                  'medicines/share.html',
                  {'medicine': medicine, 'form': form, 'sent': sent})


def profile(request):
    return render(request, "profile.html", {'user': request.user})


def register(request):
    if request.method == "POST":
        form = forms.UserRegistrationForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            new_user = form.save(commit=False)
            new_user.set_password(cd['password'])
            new_user.save()
            models.Profile.objects.create(user=new_user)

            return render(request, "registration_complete.html",
                          {"user": new_user})

    else:
        form = forms.UserRegistrationForm()
    return render(request, "register.html", {'form': form})


def edit_profile(request):
    if request.method == "POST":
        user_form = forms.UserEditForm(request.POST, instance=request.user)
        profile_form = forms.ProfileEditForm(request.POST,
                                             instance=request.user.profile,
                                             files=request.FILES)
        if all((user_form.is_valid(), profile_form.is_valid())):
            user_form.save()
            if not profile_form.cleaned_data['photo']:
                profile_form.cleaned_data['photo'] = request.user.profile.photo
            profile_form.save()
            return render(request, "profile.html", {'user': request.user})

    else:
        user_form = forms.UserEditForm(instance=request.user)
        profile_form = forms.ProfileEditForm(request.POST, instance=request.user.profile)

    return render(request, "edit_profile.html", {'user_form': user_form,
                                                 'profile_form': profile_form})


def create_medicine(request):
    if request.method == "POST":
        medicine_form = forms.MedicineForm(request.POST)
        if medicine_form.is_valid():
            new_medicine = medicine_form.save(commit=False)
            new_medicine.author = User.objects.first()
            new_medicine.slug = new_medicine.title.replace(" ", "-")
            new_medicine.save()

            return render(request, "medicines/detailed_medicine.html",
                          {"medicine": new_medicine})

    else:
        medicine_form = forms.MedicineForm()

    return render(request,
                  'medicines/create.html',
                  {'form': medicine_form})

project/templates/medicines/all_medicines.html
{% extends 'base.html' %}

{% block title %}
    All Medicines
{% endblock %}

{% block body %}
    <h1> Все препараты </h1>
    {% for medicine in page_object.object_list %}
        <div class="card">
            <div class="card-body">
                <h2 class="card-title">{{ medicine.title }}</h2>
                <p class="card-text">    {{ medicine.body|truncatewords:15 }}  </p>
                <a href="{{ medicine.get_absolute_url }} " class="btn btn-light"> Подробнее </a><br>
            </div>
        </div>
        <br>
    {% endfor %}
    <div class="container-flex mt-5" >
        <div class="row" >
            <div class="col-6 offset-md-2" >
                {% if is_paginated %}
                    <nav aria-label="Page navigation example" >
                    <ul class="pagination" >
                        <li class="page-item {% if not prev_url %} disabled {% endif %}"  >
                            <a class="page-link" href="{{prev_url }}" tabelindex="-1">Предыдущая</a>
                        </li>
                        {% for n in page_object.paginator.page_range %}
                            {% if page_object.number == n %}
                                <li class="page-item active">
                                    <a class="page-link" href="?page={{ n }}" >{{ n }}
                                        <span class="sr-only">(current)</span></a>
                                </li>
                            {% elif n > page_object.number|add:-3 and page_object.number|add:3 %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{ n }}" >{{ n }}</a>
                                </li>
                            {% endif %}
                        {% endfor %}
                        <li class="page-item {% if not next_url %} disabled {% endif %}">
                            <a class="page-link" href="{{next_url }}" tabelindex="-1" >Следуюшая</a>
                        </li>
                    </ul>
                {% endif %}
                <h4 class="map - right">Аптеки</h4><br>
                <script type="text/javascript" charset="utf-8" async src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3A4432f6a6f9f33dbd10155c758e77ead2ddf1a17ab393eee4c7d1663bba5b9376&amp;width=654&amp;height=561&amp;lang=ru_RU&amp;scroll=true"></script>        </div>
        </div>

    </div>
    </div>
    </div>

{% endblock %}

project/templates/medicines/create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Create medicine
{% endblock %}

{% block body %}
        <h1>Добавление нового препарата</h1>
        <form action="." method="post">
            {{ form | crispy}}
            {% csrf_token %}
            <input type="submit" value="Создать" class="btn btn-light">
        </form>
{% endblock %}

project/templates/medicines/detailed_medicine.html
{% extends 'base.html' %}

{% block title %}
    {{ medicine.title }}
{% endblock %}

{% block body %}
    <a href="{% url "project:all_medicines" %}" class="btn btn-light"> Ко всем препаратам </a>
    <h1>{{ medicine.title }}</h1>
    <p>{{ medicine.SUPPLIED_TYPE }}</p>

    <p>{{ medicine.body }}</p>

    <h5> В наличии:  {{ medicine.PHARMACY }} </h5>
    Последнее обновление: {{ medicine.updated }}
    <a href="{% url "project:share_medicine" medicine.id %}" class="btn btn-light">Share</a>

{% endblock %}

project/templates/medicines/share.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Share Medicine
{% endblock %}

{% block body %}
    {% if not sent %}
        <h1>Поделиться {{ medicine.title}} по электронной почте</h1>
        <form action="." method="post">
            {{ form | crispy }}
            {% csrf_token %}
            <input type="submit" value="Поделиться!" class="btn btn-light">
        </form>
    {% else %}
        Письмо было отправлено.
    {% endif %}
    <a href="{% url "project:all_medicines" %}" class="btn btn-light"> Ко всем материалам </a>
{% endblock %}